### ISSUE TITLE
Adding Dragonflydb Configuration

### ISSUE THREAD

**Issue by RatulSaqibKhan** [a-h-abid/docker-commons#13]
As dragonfly db is emerging as an alternative to redis, I think the relevant configuration can be added in this repo.
Please check the PR #14

**Comment by a-h-abid** [comment]
@RatulSaqibKhan ... check the PR comments for feedbacks.

**Comment by RatulSaqibKhan** [comment]
Updated the PR with removal of secret in .env.example for Dragonfly

**Comment by a-h-abid** [comment]
> Updated the PR with removal of secret in .env.example for Dragonfly

Check for more feedbacks shared.

**Comment by RatulSaqibKhan** [comment]
Updated the dragonfly specific environment file

**Comment by a-h-abid** [comment]
Merged
